name: CryptoBot Daily Update

on:
  schedule:
    # تشغيل يوميًا الساعة 10 صباحًا UTC
    - cron: '0 10 * * *'
  workflow_dispatch: # لتشغيل يدوي أيضًا

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install requests
      run: pip install requests

    - name: Run Crypto Bot Script
      run: python KobraCryptoAlertsBot.py
